### PR TITLE
Fix bug with clear for user not clearing

### LINKED ISSUE #150: Clear for a single user throws an error
When you try to clear a user's message with <code>\clear -u [@user]</code> the bot does not respond and throws the following error in the terminal: <code>[ERROR] [tried to log empty message]</code>

### PR DESCRIPTION
**Pull request by StephanoMehawej**
closes #150

### CODE REVIEW

File: src/commands/CommandClear.java [hunk 1]
```diff
@@ -228,7 +228,7 @@ public String getCommandDescription(){
 					false, "i", "interactive"),
 			new ParametersHelp(
 				"Allows you to delete the messages of a user you specifie.",
-				false, "u", "user"),
+				true, "u", "user"),
```
Comment (V-ed) [inline src/commands/CommandClear.java]: You could've completely removed the boolean parameter but this works too haha
